name: CI JUnit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  JUnitJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
    
      - run: mvn test
